src/Entity/User.php
<?php

namespace App\Entity;

use App\Entity\Traits\SlugifyTrait;
use App\Entity\Traits\TimeStampableTrait;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 * @ORM\HasLifecycleCallbacks()
 * @UniqueEntity(
 *  fields={"email"},
 *  message="Cet email a déjà été utilisé, merci de le modifier"
 * )
 * @UniqueEntity(
 *     fields = {"pseudo"},
 *     message = "Ce pseudo est déjà utilisé !"
 * )
 * @UniqueEntity(
 *     fields={"firstname", "lastname"},
 *     errorPath="lastname",
 *     message="Ce nom et ce prénom existe déjà dans notre liste d'utilisateurs."
 * )
 */
class User implements UserInterface
{
    use TimeStampableTrait;
    use SlugifyTrait;
    
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank()
     */
    private $firstname;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank()
     */
    private $lastname;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $pseudo;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Email(message="Veuillez renseigner un email valide")
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $avatar;

    /**
    * @ORM\Column(type="string", length=255)
    * @Assert\Length(
     *      min = 8,
     *      max = 200,
     *      minMessage = "Votre mot de passe doit contenir au moins {{ limit }} caractères.",
     *      maxMessage = "Votre mot de passe ne peut pas contenir plus de {{ limit }} caractères"
     * )
     * @Assert\Regex(
     *     pattern = "^(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9])(?=.*\W)^",
     *     match = true,
     *     message = "Votre mot de passe doit contenir au moins une minuscule, une majuscule, un chiffre et un caractère spécial."
     * )
    */
    private $hash;
    
    /**
     * Not reliable to ORM
     * @Assert\EqualTo(
     *      propertyPath="hash",
     *      message="Le mot de passe n'est pas identique"
     * )
     */
    public $passwordConfirm;

    /**
     * @ORM\Column(type="boolean")
     */
    private $active;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Post", mappedBy="author", orphanRemoval=true)
     */
    private $posts;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $slug;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Role", mappedBy="Users")
     */
    private $userRoles;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Comment", mappedBy="author", orphanRemoval=true)
     */
    private $comments;
   

    public function __construct()
    {
        $this->posts = new ArrayCollection();
        $this->userRoles = new ArrayCollection();
        $this->comments = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(string $firstname): self
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getLastname(): ?string
    {
        return $this->lastname;
    }

    public function setLastname(string $lastname): self
    {
        $this->lastname = $lastname;

        return $this;
    }

    public function getFullname(): ?string
    {
        return $this->getFirstname() . " " . $this->getLastName();
    }

    public function getPseudo(): ?string
    {
        return $this->pseudo;
    }

    public function setPseudo(string $pseudo): self
    {
        $this->pseudo = $pseudo;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getAvatar(): ?string
    {
        return $this->avatar;
    }

    public function setAvatar(?string $avatar): self
    {
        $this->avatar = $avatar;

        return $this;
    }

    public function getHash(): ?string
    {
        return $this->hash;
    }

    public function setHash(string $hash): self
    {
        $this->hash = $hash;

        return $this;
    }

    public function getActive(): ?bool
    {
        return $this->active;
    }

    public function setActive(bool $active): self
    {
        $this->active = $active;

        return $this;
    }

    public function getCookie(): ?string
    {
        return $this->cookie;
    }

    public function setCookie(?string $cookie): self
    {
        $this->cookie = $cookie;

        return $this;
    }

    /**
     * @return Collection|Post[]
     */
    public function getPosts(): Collection
    {
        return $this->posts;
    }

    public function addPost(Post $post): self
    {
        if (!$this->posts->contains($post)) {
            $this->posts[] = $post;
            $post->setAuthor($this);
        }

        return $this;
    }

    public function removePost(Post $post): self
    {
        if ($this->posts->contains($post)) {
            $this->posts->removeElement($post);
            // set the owning side to null (unless already changed)
            if ($post->getAuthor() === $this) {
                $post->setAuthor(null);
            }
        }

        return $this;
    }

    public function getRoles()
    {
        $roles = $this->userRoles->map(function ($role) {
            return $role->getTitle();
        })->toArray();
        
        $roles[] = 'ROLE_USER';

        return $roles;
    }

    public function getPassword()
    {
        return $this->hash;
    }

    public function getSalt() {}

    public function getUsername()
    {
        return $this->email;
    }

    public function eraseCredentials() {}

    /**
     * @return Collection|Role[]
     */
    public function getUserRoles(): Collection
    {
        return $this->userRoles;
    }

    public function addUserRole(Role $userRole): self
    {
        if (!$this->userRoles->contains($userRole)) {
            $this->userRoles[] = $userRole;
            $userRole->addUser($this);
        }

        return $this;
    }

    public function removeUserRole(Role $userRole): self
    {
        if ($this->userRoles->contains($userRole)) {
            $this->userRoles->removeElement($userRole);
            $userRole->removeUser($this);
        }

        return $this;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setAuthor($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->contains($comment)) {
            $this->comments->removeElement($comment);
            // set the owning side to null (unless already changed)
            if ($comment->getAuthor() === $this) {
                $comment->setAuthor(null);
            }
        }

        return $this;
    }
}

src/Controller/PostController.php
<?php

namespace App\Controller;

use DateTime;
use App\Entity\Post;
use App\Entity\Image;
use App\Form\PostType;
use App\Entity\Comment;
use App\Form\CommentType;
use App\Service\FileService;
use App\Service\VideoService;
use App\Entity\Traits\PostTrait;
use App\Service\PurifierService;
use App\Repository\PostRepository;
use App\Service\PaginationService;
use App\Repository\ImageRepository;
use App\Repository\StatusRepository;
use App\Service\FileUploaderService;
use App\Repository\CategoryRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Form\Extension\Core\Type\HiddenType;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\DependencyInjection\ParameterBag\ParameterBagInterface;

class PostController extends AbstractController
{
    use PostTrait;

    /**
     * Create a new Post
     * @Route("tricks/new", name="trick_create")
     * @IsGranted("ROLE_USER")
     * @return Response
     */
    public function create(
        Request $request,
        PurifierService $purifier,
        EntityManagerInterface $manager,
        VideoService $videoService,
        FileUploaderService $fileUploader
    ) {

        $post = new Post();
        $post->setDatePublish(new \DateTime());

        $form = $this->createForm(PostType::class, $post);
        $form->remove('author');
        $form->handleRequest($request);
 
        if ($form->isSubmitted() && $form->isValid()) {
            
            //Cover image
            $coverImage = $form['coverImage']->getData();
            if ($coverImage === null) {
                $defaultImage = 'default-trick.jpg';
                $post->setCoverImage($defaultImage);
            } else {
                $coverImageFilename = $fileUploader->upload($coverImage, 'tricks');
                $post->setCoverImage($coverImageFilename);
            }

            //Gallery images
           $aImages = $request->files->get('images');
            $i = 1;
            foreach ($aImages as $image) {
                
                $GalleryFilename = $fileUploader->upload($image, 'tricks');
                $image = new Image();
                $image->setName($GalleryFilename);
                $post->addImage($image);
                $i++;
            }
            
            //Videos
            $result = $videoService->addVideosToPost($post, $form['videos']->getData());
            if (!empty($result)) {
                $this->addFlash($result['label'], $result['message']);
            }

            // ContentSanitize
            $content = $purifier->purify($form['content']->getData());
            $post->setContent($content);

            // Author
            $post->setAuthor($this->getUser());

            $manager->persist($post);
            $manager->flush();

            $this->addFlash(
                "success",
                "Le trick <strong>{$post->getTitle()}</strong> a bien été enregistré !"
            );

            // Redirection to post if datePublish not greater than today
            if ($post->getDatePublish() <= new DateTime('now') && $post->getActive()) {
                return $this->redirectToRoute('trick_show', [
                    'slug' => $post->getSlug()
                ]);
            } else {
                return $this->redirectToRoute('trick_edit', [
                    'slug' => $post->getSlug()
                ]);
            }
        }
        return $this->render('front/pages/posts/new.html.twig', [
            'form' => $form->createView(),
            'footerPost' => $this->getPostByCatSlug($this->getParameter('about_slug'))
        ]);
    }

    /**
     * Edit post
     * @Route("tricks/{slug}/edit", name="trick_edit")
     * @Security("is_granted('ROLE_USER') and user === post.getAuthor()", message="Cette annonce ne vous appartient pas, vous ne pouvez pas la modifier")
     * @return void
     */
    public function edit(
        Post $post,
        Request $request,
        PurifierService $purifier,
        FileService $fileService,
        ImageRepository $imageRepo,
        VideoService $videoService,
        EntityManagerInterface $manager,
        FileUploaderService $fileUploader
    ) {
        //Paths
        $relativePath = $this->getParameter('tricks_img_rel_path');
        $absolutePath = $this->getParameter('tricks_directory');

        // CoverImage
        $aImageCover = [];

        // Gallery images
        $aImages = $imageRepo->findBy(array('post' => $post->getId()));
        $aImagesUrl = [];
        $aImagesInfos = [];
        $aImagesIds = [];

        foreach ($aImages as $image) {
            array_push($aImagesUrl, $relativePath.$image->getName());
            array_push(
                $aImagesInfos,
                [
                    'size' => filesize($absolutePath. $image->getName()),
                    'id' => $image->getId()
                ]
            );
            array_push($aImagesIds, $image->getId());
        }

        // Form
        $form = $this->createForm(PostType::class, $post);
        $form->add('old-images', HiddenType::class, ['mapped' => false, 'data' => implode(",", $aImagesIds)]);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            //Cover image
            $coverImage = $form['coverImage']->getData();
            $oldCoverImage = $post->getCoverImage();
            
            if ($coverImage !== null) {
                $trickImageFilename = $fileUploader->upload($coverImage, 'tricks');
                $post->setCoverImage($trickImageFilename);
            }
            if ($coverImage == null && $form['coverChanged']->getData() == 1) {
                $post->setCoverImage($coverImage);
                if (!empty($oldCoverImage)) {
                    $fileService->deleteFile($this->getParameter('tricks_directory') . $oldCoverImage);
                }
            }

            //Gallery images
            $aNewImages = $request->files->get('images');
            $aOldsImages = !empty($form['old-images']->getData()) ? explode(",", $form['old-images']->getData()) : array();

            if (count($aNewImages)) {
                $i = 1;
                foreach ($aNewImages as $image) {
                    $GalleryFilename = $fileUploader->upload($image, 'tricks');
                    $image = new Image();
                    $image->setName($GalleryFilename);
                    $post->addImage($image);
                    $i++;
                }
            }

            if (count($aOldsImages)) {

                //Keep old images not deleted
                $j = 1;
                foreach ($aOldsImages as $idImage) {
                    $image = $imageRepo->find($idImage);
                    $post->addImage($image);
                    $j++;
                }

                // Delete old deleted images
                $aIdsImgToDelete = array_diff($aImagesIds, $aOldsImages);
                foreach ($aIdsImgToDelete as $idImage) {
                    $imageToDel = $imageRepo->find($idImage);
                    $fileService->deleteFile($this->getParameter('tricks_directory') . $imageToDel->getName());
                }
            }

            //Videos
            $result = $videoService->addVideosToPost($post, $form['videos']->getData());
            if (!empty($result)) {
                $this->addFlash($result['label'], $result['message']);
            }
            
            //ContentSanitize
            $content = $purifier->purify($form['content']->getData());
            $post->setContent($content);

            $manager->persist($post);
            $manager->flush();

            $this->addFlash(
                "success",
                "Le trick <strong>{$post->getTitle()}</strong> a bien été modifié !"
            );

            // Redirection to post if datePublish not greater than today
            if ($post->getDatePublish() <= new DateTime('now') && $post->getActive()) {
                return $this->redirectToRoute('trick_show', [
                    'slug' => $post->getSlug()
                ]);
            } else {
                return $this->redirectToRoute('trick_edit', [
                    'slug' => $post->getSlug()
                ]);
            }
        }

        if (!empty($post->getCoverImage() && $post->getCoverImage() !== $this->getParameter('trick_cover_default'))) {
            $aImageCover['url'] = $relativePath . $post->getCoverImage();
            $aImageCover['size'] = filesize($absolutePath. $post->getCoverImage());
        }

        return $this->render('front/pages/posts/edit.html.twig', [
            'form' => $form->createView(),
            'urls' => json_encode($aImagesUrl),
            'imagesInfos' => json_encode($aImagesInfos),
            'imageCover' => json_encode($aImageCover),
            'post' => $post,
            'footerPost' => $this->getPostByCatSlug($this->getParameter('about_slug'))
        ]);
    }

    /**
     * Show an post
     * @Route("/tricks/{slug}/{page<\d+>?1}", name="trick_show")
     * @param PaginationService $pagination
     * @param Post $oPost
     * @return Response
     */
    public function show(
        Post $oPost,
        $page,
        Request $request,
        PostRepository $repoPost,
        PaginationService $pagination,
        CategoryRepository $repoCat,
        StatusRepository $repoStatus,
        EntityManagerInterface $manager,
        ParameterBagInterface $params
    ) {
        // Redirection to 404 if datePublish is greater than today and user isn't author or author is inactive

templates/front/pages/posts/_trick-card.html.twig
{% set postUrl = path('trick_show', {'slug': post.slug}) %}
{% set nbComments = 0 %}
{% for comment in post.comments %}
    {% if comment.status.id == 2 and comment.author.active %}
        {% set nbComments = nbComments + 1 %}
    {% endif %}
{% endfor %}

<div class="col-12 col-lg-4 col-md-6 grid-item margin-30px-bottom">
    <div class="card  blog-post bg-light-gray inner-match-height d-flex justify-content-center">

        <!-- Cover image -->
        <div class="blog-post-images overflow-hidden position-relative">
            <a href="{{ postUrl }}">
                <img 
                    src="{% if post.coverImage is null %} {{ tricks_dir ~ trick_default }} {% else %} {{ tricks_dir ~ post.coverImage }} {% endif%}" 
                    alt="Image tricks {{ post.category.title }}">
                <div class="blog-hover-icon">
                    <span class="text-extra-large font-weight-300">+</span>
                </div>
            </a>
        </div>
       
        <div class="card-body post-details padding-20px-top padding-40px-all md-padding-20px-all">

             <!-- Metas -->
            <div class="post-meta">
                <span class="post-category">
                    <a href="{{ path('category_show', {'slug': post.category.slug}) }}" class="text-medium-gray">
                        {{ post.category.title }}
                    </a>
                </span>
                 <span class="post-date">
                    {{ post.datePublish | format_datetime('long', 'none', locale='fr') }}
                 </span>
            </div>


            <!-- Content -->
            <div class="post-content">
                <a href="{{ postUrl }}" class="alt-font post-title width-100 d-block lg-width-100 margin-15px-bottom">
                    <!-- Title -->
                    <h3 class="text-medium text-extra-dark-gray margin-15px-bottom margin-5px-top">{{ post.title }}</h3>
                
                    <!-- Heading -->
                    <p class="text-dark-gray">
                        {% if post.heading | length %}
                            {{ post.heading | u.truncate(160, '...') }}
                        {% else %}
                            {{ post.content | striptags | trim | u.truncate(160, '...')}} 
                        {% endif %}
                    </p>
                </a>
            </div>

            <!-- Status -->
            {% if app.request.attributes.get('_route') == 'account_index'%}
            <div class="blogPostStatus">
                {% if post.active and date(post.datePublish) < date()  %}
                    <span class="badge badge-success rounded"><i class="fas fa-wifi"></i> En ligne </span>
                {% elseif post.active and date(post.datePublish) > date() %}
                    <span class="badge badge-warning rounded"><i class="fas fa-clock"></i> Programmé </span>
                {% else %}
                    <span class="badge badge-dark rounded"><i class="fas fa-mask"></i> Hors ligne </span>
                {% endif %}
            </div>
            {% endif %}

        </div>

       
        <div class="card-footer text-muted author">

             <!-- Actions buttons -->
            <div class="text-center">
                <a href="{{ postUrl }}" class="btn btn-secondary btn-small">Lire</a>
                {% if app.user and app.user == post.author %}
                    <a href="{{ path('trick_edit',{'slug' : post.slug}) }}" class="btn btn-secondary btn-small">Editer</a>
                {% endif %}
            </div>

             <!-- Author -->
            <div class="text-medium-gray text-extra-small d-inline-block d-flex justify-content-between margin-15px-top">
                <div class="post-meta-info">
                    <a href="{{ path('user_show', {'slug': post.author.slug}) }}" class="text-medium-gray">
                        <i class="fas fa-user"></i> {{ post.author.fullname | title }}
                    </a>
                </div>
                <div class="post-meta-info post-date">
                    <i class="fas fa-edit"></i> {{ post.datePublish | format_datetime('long', 'none', locale='fr') }}
                </div>
                <div class="post-meta-info last post-comments">
                    <a href="{{ postUrl }}#comments" title="Commentaires" class="text-medium-gray">
                        {{ nbComments }} <i class="far fa-comment-alt"></i>
                    </a>
                </div>
            </div>
        </div>

    </div>
</div>

templates/front/pages/posts/category.html.twig
{% extends "front/base-front.html.twig" %}

{% block body %}
 <section>
    <div class="container">

        {% include "front/blocs/header.html.twig" %}

        <div class="row">
            <article class="col-12 col-lg-9 mb-5 md-padding-15px-lr">

                {% if pagination.data | length %}
                    {% for post in pagination.data %}
                        {% set postUrl = path('trick_show', {'slug': post.slug}) %}
                        {% set nbComments = 0 %}
                        {% for comment in post.comments %}
                            {% if comment.status.id == 2 %}
                                {% set nbComments = nbComments + 1 %}
                            {% endif %}
                        {% endfor %}

                        <div class="blog-post-content d-flex align-items-center flex-wrap margin-60px-bottom padding-60px-bottom border-bottom border-color-extra-light-gray md-margin-30px-bottom md-padding-30px-bottom md-no-border">
                            
                            <!-- Cover image -->
                            <div class="col-12 col-lg-5 blog-image p-0 md-margin-30px-bottom sm-margin-20px-bottom margin-45px-right md-no-margin-right">
                                <a href="{{ postUrl }}">
                                    <img 
                                        src="{% if post.coverImage is null %} {{ tricks_dir ~ trick_default }} {% else %} {{ tricks_dir ~ post.coverImage }} {% endif%}" 
                                        alt="Image de couverture de l'article #{{ post.id}}" 
                                    >
                                </a>
                            </div>
                            
                             <!-- Content -->
                            <div class="col-12 col-lg-6 blog-text p-0">
                                <div class="content margin-20px-bottom text-md-left text-center">
                                    
                                    <!-- Title -->
                                    <a href="{{ postUrl }}" class="text-extra-dark-gray margin-5px-bottom alt-font font-weight-600 d-inline-block text-">
                                        <h3 class="text-medium text-extra-dark-gray margin-15px-bottom margin-5px-top">{{ post.title }}</h3>
                                    </a>
                                    
                                    <!-- Metas -->
                                    <div class="row no-gutters post-meta mb-md-0 mb-sm-2">
                                        <div class="col-12 text-md-left text-sm-center">
                                            <span class="post-category">
                                                <a href="{{ path('user_show', {'slug': post.author.slug}) }}" class="text-medium-gray">{{ post.author.fullname | title }}</a>
                                            </span>
                                            <span class="post-date text-medium-gray">{{ post.dateCreate | format_datetime('long', 'none', locale='fr') }}</span>
                                            <a href="{{ postUrl }}#comments" title="Commentaires" class="text-medium-gray">
                                                {{ nbComments }} <i class="far fa-comment-alt"></i>
                                            </a>
                                        </div>
                                    </div>

                                    <!-- Content -->
                                    <div class="row no-gutters">
                                        <div class="col-12 text-md-left text-sm-center">
                                            <p class="text-dark-gray m-0 width-95">
                                                {% if post.heading | length %}
                                                    {{ post.heading | u.truncate(160, '...') }}
                                                {% else %}
                                                    {{ post.content | striptags | trim | u.truncate(160, '...')}} 
                                                {% endif %}
                                            </p>
                                        </div>
                                        <div class="col-md-9 col-12 mt-2">
                                            <a class="btn btn-very-small btn-dark-gray text-uppercase " href="{{ postUrl }}">Lire</a>
                                            {% if app.user and app.user == post.author %}
                                                <a href="{{ path('trick_edit',{'slug' : post.slug}) }}" class="btn btn-very-small btn-dark-gray text-uppercase">Editer</a>
                                            {% endif %}
                                        </div>
                                        {% if app.user and app.user == post.author %}
                                            <div class="col-md-3 col-12 blogPostStatus align-self-center mt-2">
                                                {% if post.active and date(post.datePublish) < date()  %}
                                                    <span class="badge badge-success rounded"><i class="fas fa-wifi"></i> En ligne </span>
                                                {% elseif post.active and date(post.datePublish) > date() %}
                                                    <span class="badge badge-warning rounded"><i class="fas fa-clock"></i> Programmé </span>
                                                {% else %}
                                                    <span class="badge badge-dark rounded"><i class="fas fa-mask"></i> Hors ligne </span>
                                                {% endif %}
                                            </div>
                                        {% endif %}
                                    </div>
                                </div>
                            </div>
                            
                        </div>
                    {% endfor %}

                    {{ pagination.display }}

                {% else %}
                    <p>Cette catégorie ne contient aucun trick pour l'instant</p>
                    <p>Repassez plus tard ou ajoutez en un</p>
                    <a href="{{ path('trick_create') }}" class="btn btn-primary">Poster un trick</a>
                {% endif %}  
                   
            </article>

            <!-- Aside -->                
            {% include "front/_partials/_aside.html.twig" %}
        </div>
    </div>
</section>
{% endblock %}